version: "3.8"

services:
  migrate:
    image: cuckoo-echo-migrate:latest
    deploy:
      replicas: 0

  api-gateway:
    image: cuckoo-echo-api-gateway:latest

  admin-service:
    image: cuckoo-echo-admin-service:latest
    deploy:
      replicas: 0

  chat-service:
    image: cuckoo-echo-chat-service:latest
    deploy:
      replicas: 0

  knowledge-pipeline:
    image: cuckoo-echo-knowledge-pipeline:latest
    deploy:
      replicas: 0

  seed:
    image: cuckoo-echo-seed:latest
    deploy:
      replicas: 0