apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cuckoo-echo
  labels:
    app: cuckoo-echo
spec:
  selector:
    matchLabels:
      app: api-gateway
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
