"""Milvus client utilities for Cuckoo-Echo.

Provides MilvusClient connection helper and knowledge_chunks collection
creation with dense (HNSW) + sparse (BM25) hybrid search support.
"""

from __future__ import annotations

import structlog
from pymilvus import (
    CollectionSchema,
    DataType,
    FieldSchema,
    Function,
    FunctionType,
    MilvusClient,
)

from shared.config import get_settings

log = structlog.get_logger()

COLLECTION_NAME = "knowledge_chunks"


def get_milvus_client() -> MilvusClient:
    """Return a MilvusClient connected to the configured Milvus instance.

    Reads ``MILVUS_URI`` from pydantic-settings (default ``http://localhost:19530``).
    """
    uri = get_settings().milvus_uri
    log.info("connecting_to_milvus", uri=uri)
    return MilvusClient(uri=uri)


def create_knowledge_chunks_collection(client: MilvusClient | None = None) -> None:
    """Create the *knowledge_chunks* collection with hybrid search support.

    Schema fields:
        - id: primary key (VARCHAR)
        - tenant_id: partition key for multi-tenant isolation (VARCHAR)
        - doc_id: reference to knowledge_docs table (VARCHAR)
        - chunk_text: text content with Chinese analyzer (VARCHAR)
        - dense_vector: FLOAT_VECTOR dim=1536 for embedding search
        - sparse_vector: SPARSE_FLOAT_VECTOR auto-generated by BM25 function
        - created_at: unix timestamp (INT64)

    Indexes:
        - HNSW on dense_vector (COSINE, M=16, efConstruction=200)
        - SPARSE_INVERTED_INDEX on sparse_vector (BM25)
    """
    if client is None:
        client = get_milvus_client()

    # -- Schema --
    schema = CollectionSchema(fields=[
        FieldSchema("id", DataType.VARCHAR, max_length=64, is_primary=True),
        FieldSchema("tenant_id", DataType.VARCHAR, max_length=64, is_partition_key=True),
        FieldSchema("doc_id", DataType.VARCHAR, max_length=64),
        FieldSchema(
            "chunk_text",
            DataType.VARCHAR,
            max_length=4096,
            enable_analyzer=True,
            analyzer_params={"type": "chinese"},
        ),
        FieldSchema("dense_vector", DataType.FLOAT_VECTOR, dim=1536),
        FieldSchema("sparse_vector", DataType.SPARSE_FLOAT_VECTOR),
        FieldSchema("created_at", DataType.INT64),
    ])

    # -- BM25 function: chunk_text → sparse_vector --
    bm25_function = Function(
        name="bm25",
        function_type=FunctionType.BM25,
        input_field_names=["chunk_text"],
        output_field_names=["sparse_vector"],
    )
    schema.add_function(bm25_function)

    log.info("creating_collection", name=COLLECTION_NAME)

    # -- Index params --
    index_params = client.prepare_index_params()
    index_params.add_index(
        field_name="dense_vector",
        index_type="HNSW",
        metric_type="COSINE",
        params={"M": 16, "efConstruction": 200},
    )
    index_params.add_index(
        field_name="sparse_vector",
        index_type="SPARSE_INVERTED_INDEX",
        metric_type="BM25",
    )

    # -- Create collection --
    client.create_collection(
        collection_name=COLLECTION_NAME,
        schema=schema,
        index_params=index_params,
        num_partitions=64,
    )

    log.info("collection_created", name=COLLECTION_NAME, num_partitions=64)
